// Old WooCommerce URL support. Maps are generated by scripts/build-legacy-maps.mjs.
import slugToId from "./data/legacy-slugs.json";
import categoryMap from "./data/legacy-categories.json";

const idBySlug = new Map<string, string>(
  Object.entries(slugToId as Record<string, string>).map(([id, slug]) => [slug, id])
);
const categories = categoryMap as Record<string, string>;

export function normalizeLegacySlug(raw: string): string {
  let s = raw;
  // Next may or may not have decoded the param; decode until stable (max twice).
  for (let i = 0; i < 2; i++) {
    try {
      const d = decodeURIComponent(s);
      if (d === s) break;
      s = d;
    } catch {
      break;
    }
  }
  return s.normalize("NFC").replace(/\/+$/, "");
}

export function legacyBookId(rawSlug: string): string | null {
  return idBySlug.get(normalizeLegacySlug(rawSlug)) ?? null;
}

export function legacyCategoryName(rawSlug: string): string | null {
  return categories[normalizeLegacySlug(rawSlug)] ?? null;
}
